### ISSUE TITLE
conda-forge artifacts on win32 are not superseding repo.continuum.io

### ISSUE THREAD

**Issue by wesm** [conda-forge/thrift-feedstock#4]
See https://ci.appveyor.com/project/conda-forge/ibis-framework-feedstock/build/1.0.15/job/c3vb3l6k4gcd41bh

It seems the thrift package from repo.continuum.io on this build configuration is broken. @jakirkham @msarahan @mariusvniekerk this may be fixable if we set this recipe to track the vc9 feature on `[win and py2k]`, do you agree?

**Comment by mariusvniekerk** [comment]
This may also be the same as #3.  This seems to be somewhat caused by conda-build.  We might be able to fix this with a postprocessing thing that removes all the files that should not be part of the artifact

**Comment by wesm** [comment]
If you look at that appveyor build log, it's installing thrift from defaults instead of conda-forge

**Comment by mariusvniekerk** [comment]
Would bumping the build number ensure the correct override? @ericdill

**Comment by ericdill** [comment]
I am not familiar with `vc` features on windows.  The line

```
    thrift-0.9.3               |            vc9_0         9.0 MB  defaults
```

would suggest that this is picking up the build from defaults with a build number of `0` while the conda-forge recipe has a build number of `1` (https://github.com/conda-forge/thrift-feedstock/blob/master/recipe/meta.yaml#L11).  Bumping the build number to `2` is unlikely to solve this problem
